### ISSUE TITLE
Right click doesn't show expected rabbitvcs menu in nautilus

### ISSUE THREAD

**Issue by buildcomplete** [CloCkWeRX/rabbitvcs-svn-mirror#1]
I have a directory under svn version control.

rabbitvcs shows the icon overlays with colors, but when I right click a folder, I doesn't show the menu I would expect from the image here: http://wiki.rabbitvcs.org/wiki/about/screenshots

Nautilus is version 3.10.1

**Comment by CloCkWeRX** [comment]
Probably want https://github.com/rabbitvcs/rabbitvcs
